---
title: "Slides for MA336 Statistics"
date: "Fall 2023"
output:
  markdown::html_format
---

## List of slides

- [Topic 1: Statistical Studies](Topic-1-Statistical-Studies.html)

- [Topic 2: Summarizing Data Graphically](Topic-2-Graphical-Descriptions.html)

- [Topic 3: Summarizing Data Numerically](Topic-3-Numercial-Descriptions.html)

- [Topic 4: Linear Relationship](Topic-4-Linear-Relationship.html)

- [Topic 5: Introduction to Probability](Topic-5-Probability.html)

- [Topic 6: Two-way Tables](Topic-6-Two-Way-Tables.html)

- [Topic 7: Discrete Random Variables](Topic-7-Discrete-Random-Variables.html)

- [Topic 8: Continuous Random Variables](Topic-8-Continuous-Random-Variables.html)

- [Topic 9: Sampling Distribution](Topic-9-Sampling-Distributions.html)

- [Topic 10: Confidence Interval for a Mean](Topic-10-Confidence-Intervals-Mean.html)

- [Topic 11: Confidence Interval for a Proportion](Topic-11-Confidence-Intervals-Proportion.html)

- [Topic 12: Concepts of Hypothesis Testing](Topic-12-Concepts-of-Hypothesis-Testing.html)

- [Topic 13: Hypothesis Testing for a Mean or a Proportion](Topic-13-Hypothesis-Testing-Mean-Proportion.html)

- [(**optional**) Topic 14: Hypothesis Testing for a Median](Topic-14-Confidence-Intervals-Median.html)
