name: Deploy html slides to GitHub Pages
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy HTML files to public folder for deployment
        run: |
          mkdir -p public
          find . -maxdepth 1 -name '*.html' -exec cp {} public/ \;
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        